#!/usr/bin/env node

// Copyright 2021 Sleepless Software Inc. All Rights Reserved

const http = require( "http" );

const { log5, toInt, o2j, } = require( "sleepless" );

const L = log5;


const argv = process.argv; 

const usage = function() {
    console.log( "Usage: "+argv[ 0 ]+" "+argv[ 1 ]+" root_dir [ port [ log_level ] ]" );
    process.exit( 1 );
}

const root = argv[ 2 ];

if( ! root ) {
    usage();
}

const port = toInt( argv[ 3 ] ) || 80;

const ll = toInt( argv[ 4 ] ) || 3;
L( ll ).V( "Verbosity level: "+ll );

http.createServer( ( req, res ) => {
    const handler = require( __dirname+"/basic.js" ).create( { root } );
    handler( req, res );
} ).listen( port, () => {
    L.I( "Listening on "+port+" & serving from "+o2j( root ) );
})

