#!/usr/bin/env node


// Copyright 2020
// Sleepless Software Inc.
// All Rights Reserved
// sleepless.com

const L = require( "log5" ).mkLog( "webserver: " )( 4 );

const usage = function() {
	L.E( "Usage: webserver create project_name" );
	L.E( "Usage: webserver [run] port [dir] [ watch_files(true/false) ]" );
	process.exit( 1 );
}

const argv = process.argv;
// all possible valid arg options:
// 		"node", "webserver", "create", "path"
// 		"node", "webserver", "run", 12345,
// 		"node", "webserver", "run", 12345, "path"
// 		"node", "webserver", "run", 12345, "path", "watch"
// 		"node", "webserver", 12345
// 		"node", "webserver", 12345, "path"
// 		"node", "webserver", 12345, "path", "watch"
if( argv.length < 3 ) {
	usage();
}

if( ( argv[ 2 ] | 0 ) != 0 ) {
	// first arg looks like a number, so assume it's a port number and that they want
	// the old behavior, like "webserver 12345 [ path ]"

	argv.splice( 2, 0, "run" );	// inject "run" as first arg

	if( argv.length <= 4 ) {
		argv.push( "." );		// no root dir given, so default to cwd
	}
}


let act = argv[ 2 ] || null;
if( ! act ) {
	usage();
}

if( act == "create" ) {
	const fs = require( "fs" );
	const path = require( "path" );
	const { exec } = require( "child_process" );
	let PATH = argv[3];
	let old_path = PATH;
	// use local path or absolute path
	PATH = path.resolve( PATH );

	if( !fs.existsSync(PATH) ) {
		fs.mkdir( PATH, { recursive: true }, ( err, p ) => {
			if( err ) { return L.E( err ); }
			// To copy a folder or file  
			exec(`cp -R ${__dirname}/template/* ${PATH}; cd ${PATH}; npm i;`, err => {
				if( err ) { L.E( err ); process.exit(-1); }
				L.I( `project created ${p}`);
				L.I( `To run your project: webserver run 3000 ${old_path} true`);
				process.exit(0);
			});
		})
	} else {
		console.error( `${PATH} already exists. Exiting...`);
		process.exit(-1);
	}
} else if( act == "run" ) {
	let PORT = argv[3] || 12345;
	let PATH = argv[4] || "./";
	if( PATH[ PATH.length - 1 ] != "/" )  { PATH += "/"; }

	let WATCH = argv[5];

	var http = require('http')
	var parseUrl = require('parseurl')
	var send = require('send')

	let path = require("path");
	let { spawn, exec } = require("child_process");
	let p = path.resolve(PATH);
	
	var server = http.createServer(function onRequest (req, res ) {
		let data = '';
		req.on('data', chunk => {
			data += chunk;
		})
		req.on('end', () => {
			L.D( "\t" + req.method + " " + req.url );
			req.body = data;
			dispatch( p, req, res )
		})
	});
	

	// sandbox app
	process.chdir( p );
	if( WATCH ) {
		// sandbox watch
		exec( "chmod +x ./watch", err => {
			if( err )
				L.W( "Unable to watch." );
			else {
				let proc = spawn( "./watch" );
				proc.stdout.on( "data", data => { L.I( data ); } );
				proc.stderr.on( "data", data => { L.E( data ); } );
				proc.on( "error", data => { L.E( "watcher exited" ); } );
				proc.on( "close", data => { L.V( "watcher exited" ); } );
				L.I("Watching ...");
			}
		});
	}
	server.listen( PORT, function() { 
		L.I( "\tCopyright " + (new Date() . getFullYear()) + " Sleepless Software Inc.  All Rights Reserved - sleepless.com" );
		L.I( "\tListening on port " + PORT + ", serving from directory \"" + p + "\"");
	});


	const serve_static = require("serve-static");

	let dispatch = function( root, req, res ) {
		let mod = mod_load( root );
		if( mod ) { 
			L.D( "\troot module loaded "+root );
		   	mod( req, res, (r1, r2) => {
				if( r1 && r2 ) {
					send(r1, parseUrl(r1).pathname, { root: root }).pipe(r2);
				}
			});
		} else {
			send(req, parseUrl(req).pathname, { root: root }) .pipe(res);
		}
	}

	// Tries to load path (must be a dir) as an NPM module. Returns the module or null.
	globalThis.mod_load = function( path, n ) {
		let mod = null;
		const p = require("path");
		try {
			// use local path or absolute path
			if( path && ! p.isAbsolute(path) ) { path = p.join(__dirname, path); }
			mod = require( path );
			L.D( "\tmod loaded: " +  path );
		} catch( err ) {
			// If this err.code is present, it means the module couldn't be loaded for some reason.
			// But it seems not to be there if the module loaded but got a syntax error or something,
			// which I DO want to see, so I differentiate between those two cases here.
			if( err.code == "MODULE_NOT_FOUND") {
				L.D( "\tmodule not found: " + path );
			}
			else {
				L.V( "module present but fails to load: " + path );
				L.E( err.stack );
			}
		}

		return mod;
	}
} else {
	usage();
}


