#!/bin/bash

os=`uname`
if [ "$os" = "Linux" ] ; then
	echo "Linux"
    lscmd="ls -lR --full-time"
elif [ "$os" = "Darwin" ] ; then
	echo "MacOS"
    lscmd="ls -lR -T"
else
	echo "Unrecognized OS.  Sorry."
	exit 1
fi

last=""
while true ; do
    next=`$lscmd | grep -v reload.js | sum`
	if [ "$next" != "$last" ] ; then
		last="$next"
		echo "globalThis.needs_reload = '$next';" > static/reload.js;
		cat static/reload.js
	fi
	sleep 1
done
